apiVersion: v1
kind: Pod
metadata:
  name: nginx-cmvolume
spec:
  containers:
    - name: nginx-cmvolume
      image: nginx
      #command: [ "/bin/sh", "-c", "ls /etc/lala/" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/lala
  volumes:
    - name: config-volume
      configMap:
        name: cmvolume
  restartPolicy: Never
