apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: 
     requests:
      memory: "100Mi"
      cpu: "100m"
     limits:
      memory: "200Mi"
      cpu: "200m"
    securityContext:
     capabilities:
      add: ["NET_ADMIN", "SYS_TIME"]
  dnsPolicy: ClusterFirst
  securityContext:
   runAsUser: 101
  restartPolicy: Always
status: {}
