apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      #command: ["sleep", "3600"]
      env:
      - name: option 
        valueFrom:
          configMapKeyRef:
            name: options
            key: var5
