apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  containers:
    - name: nginx-cmvolume
      image: nginx
      #command: [ "/bin/sh", "-c", "ls /etc/lala/" ]
      env:
      - name: USERNAME
        valueFrom:
         secretKeyRef:
          name: mysecret2
          key: username
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/foo
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret2
  restartPolicy: Never
