apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busy
  name: busy
spec:
  nodeSelector:
   nodeName: nginxnode
  containers:
  - image: busybox
    name: busy
    resources: {}
    args:
    - sh
    - -c
    - date;ls;sleep 3600;
    #command: ["date","sleep","3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
