apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  volumes:
  - name: empty-vol
    emptyDir: {}
  containers:
  - args:
    - sh
    - -c
    -  while true; do echo Hi I am from Master container >> /var/log/main.txt; sleep 5; done
    image: busybox
    name: busybox
    volumeMounts:
    - name: empty-vol
      mountPath: /var/log
    resources: {}
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: empty-vol
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
