apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: multi-busybox
spec:
  containers:
  - args:
    - sh
    - -c
    - ls;sleep 3600;
    image: busybox
    name: busybox1
    resources: {}
  - args:
    - sh
    - -c
    - echo Hello World;sleep 3600;
    image: busybox
    name: busybox2
    resources: 
     requests:
      cpu: ".1"
      memory: "256Mi"
     limits:
      cpu: ".2"
      memory: "1024Mi"
  - args:
    - sh
    - -c
    - echo this is the third container;sleep 3600
    image: busybox
    name: busybox3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
