apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar-busybox
  name: sidecar-busybox
spec:
  containers:
  - args:
    - sh
    - -c
    - while true; do echo ‘Hi I am from Main container’ >> /var/log/index.html; sleep 5; done;
    image: busybox
    name: sidecar-busybox
    resources: {}
    volumeMounts:
    - name: sidecar
      mountPath: /var/log 
  - image: nginx
    name: sidecar-nginx
    resources: {}
    ports:
    - containerPort: 80
    volumeMounts:
    - name: sidecar
      mountPath: /usr/share/nginx/html
  dnsPolicy: ClusterFirst
  volumes:
  - name: sidecar
    emptyDir: {}
  restartPolicy: Never
status: {}
