apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: busycron
spec:
  startingDeadlineSeconds: 17
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: busycron
    spec:
      activeDeadlineSeconds: 20
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: busycron
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
