apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-11-19T14:20:44Z"
  labels:
    run: nginx
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:run: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2020-11-19T14:20:44Z"
  name: nginx-svc
  namespace: default
  resourceVersion: "208202"
  selfLink: /api/v1/namespaces/default/services/nginx-svc
  uid: 5fc9da37-36e4-4347-a63d-b69a74115907
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
