apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: backend
  name: backend
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
    - configMapRef:
       name: db-config
    env:
    - name: DB_PASSWORD
      valueFrom:
       secretKeyRef:
        name: db-cred
        key: db-password
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
