apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busbox
  name: busbox
spec:
  volumes:
  - name: empty-vol
    emptyDir: {}
  containers:
  - image: nginx
    name: busbox
    resources: {}
    ports:
    - containerPort: 80
    volumeMounts:
    - name: empty-vol
      mountPath: /data/app
    securityContext:
      runAsGroup: 3000
      runAsUser: 0
      capabilities:
       add: ["SYS_TIME"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
