apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: data
    persistentVolumeClaim:
     claimName: task-pvc-volume
  containers:
  - image: nginx:alpine
    name: nginx
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
