apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    my-label: test
  name: bash
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - hostname > /tmp/hostname && sleep 1d
    image: bash
    name: bash
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
