apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox2
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox
    volumeMounts:
    - name: log
      mountPath: /etc/foo
    resources: {}
  dnsPolicy: ClusterFirst
  volumes:
  - name: log
    persistentVolumeClaim:
     claimName: mypvc
  restartPolicy: Never
status: {}
