apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes:
  - name: cm
    configMap:
     name: cmenv
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: cm
      mountPath: /etc/cfg
    envFrom:
    - configMapRef:
       name: cmenv
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
